[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Cobweb = "ec354790-cf28-43e8-bb59-b484409b7bad"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RegressionTables = "d519eb52-b820-54da-95a6-98e1306fdade"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
